### ISSUE TITLE
Upstream repository

### ISSUE THREAD

**Issue by gfgit** [lxqt/libdbusmenu-lxqt#8] opened 2024-02-20 10:21 UTC
Hello,
I've looked around but could not find an upstream repository for this fork.
However there are many similar repositories:

1. https://invent.kde.org/plasma/plasma-workspace/-/tree/master/libdbusmenuqt
2. https://launchpad.net/libdbusmenu-qt
3. https://github.com/deepin-community/libdbusmenu-qt
4. https://github.com/qtilities/libdbusmenu-qtilities
5. https://github.com/OpenMandrivaAssociation/libdbusmenu-qt/tree/master (contains patches)
6. https://github.com/desktop-app/libdbusmenu-qt (archived)
7. https://github.com/a17r/libdbusmenuqt
8. https://github.com/archlinux/svntogit-packages/commit/ee7106fc688937bfbe51eccb0eadca5eefd71637

Would it be worth to make a common repository which accommodates all use cases?
I bet KDE fixes could be used on LXQt too.
We could ask KDE to extract this library from inside Plasma Workspace repository and keep it as standalone repository to which we could collaborate without needing to keep a fork.
And then maybe notify other forks about this new opportunity.

What do you think?

**Comment by gfgit** [comment] 2024-02-20 10:29
Relevant KDE discussion: https://phabricator.kde.org/T13138

**Comment by stefonarch** [comment] 2024-02-20 11:09
It's in the Readme, it's a fork from 6) which is archived.

**Comment by gfgit** [comment] 2024-02-20 11:32
Ok but I think it still better to share effort with KDE devs than having another fork which possibly tries to fix same issues

**Comment by stefonarch** [comment] 2024-02-20 11:35
I've no strong opinion about that, but we already depend on KF6. The idea afaik was to have full control over it.

**Comment by tsujan** [comment] 2024-02-20 12:40
> We could ask KDE to extract this library...

IMHO, being too dependent on KDE codes isn't a good approach. KDE devs have done and are doing a great job, but since their focus is on Plasma and their manpower doesn't seem proportional to the amount of works they do, sometimes they may forget that KF is also used outside Plasma (that has happened).

Here, we already have what we need. If KDE makes fixes that are usable to us, we could adapt them.

**Comment by gfgit** [comment] 2024-02-26 20:40
Sad story. I know this was optimistic and not real world scenario.
Still I don't think KDE devs have so narrow vision, caring only about KDE.
Anyway it's just a cool idea in comunity spirit.
@yan12125 what's you opinion on this?

**Comment by redtide** [comment] 2024-02-26 22:40
> Sad story. I know this was optimistic and not real world scenario.
Still I don't think KDE devs have so narrow vision, caring only about KDE.
Anyway it's just a cool idea in comunity spirit.

What I said it's just my own opinion, I might be wrong, you can just ask them as you said. On the other hand it was also my idea initially, I thought to ask by opening an issue [here](https://invent.kde.org/frameworks/kstatusnotifieritem/-/issues), for a collaboration to maintain a shared project and use it instead incorporate the library, but I gave up because anyway KSNI is not what we want to use: it brings KWindowSystem as dependency in our projects, and 2 libraries are already too much for a QSystemTrayIcon replacement to achieve mouse wheel event handling.

**Comment by gfgit** [comment] 2024-02-27 21:50
@redtide Thanks for the invitation. I've joined the room on Matrix but my homeserver seems quite slow. I will have to change it at some point...

**Comment by redtide** [comment] 2024-02-27 23:29
it's a chat, no need for a fast connection there

**Comment by yan12125** [comment] 2024-03-01 04:15
> Here, we already have what we need. If KDE makes fixes that are usable to us, we could adapt them.

> you can just ask them as you said

I have a similiar opinion like these. I'm not against using libraries from KDE, as long as it improves over the status quo.

> 4) is a fork from this.

Just a note: it seems more like a fork from (2) than from this

**Comment by redtide** [comment] 2024-03-01 09:14
> I'm not against using libraries from KDE, as long as it improves over the status quo.

The point is that probably they don't want to keep it alive, otherwise it wouldn't make sense for them to incorporate a part of it (menu exporter, removing the importer) [in their KSNI](https://github.com/KDE/kstatusnotifieritem/tree/master/src/libdbusmenu-qt). The version listed above (the first of the list) has the last commit from 2 years ago... though probably should be to take as reference because might have some other improvements too.

> Just a note: it seems more like a fork from (2) than from this

@stefonarch we (@sebholt and I) haven't forked the LXQt version, because it's a fork of <https://github.com/desktop-app/libdbusmenu-qt>, which IIRC has some bugs; which is also the one used on Arch, the [Qt6 version](http://archlinux.org/packages/libdbusmenu-qt6) is broken, we forked it directly from <https://github.com/unity8-team/libdbusmenu-qt> and added some menu exporter improvements from the one incorporated in KSNI.

**Comment by Thaodan** [comment] 2024-03-14 11:31
I'm currently porting a few plasma plugins to Qt6.
One of them also depends on this library which right now uses an in-tree copy of the library similar to Plasma.
It would be great to not bundle the library.

Is the version of the lib in this repository working the same way as the original?

**Comment by redtide** [comment] 2024-03-14 11:58
> I'm currently porting a few plasma plugins to Qt6. One of them also depends on this library which right now uses an in-tree copy of the library similar to Plasma. It would be great to not bundle the library.
> 
> Is the version of the lib in this repository working the same way as the original?

Depends on what you mean with "original", the original one was started more than 10 years ago by Aurélien Gâteau, at that time AFAIK KDE developer, then changed repositories over time. This is a fork of one of the variations of it. IIUC you are asking the same question me (somewhere else) and @gfgit did (here).
IIRC @tsujan [was against](https://github.com/lxqt/lxqt-panel/issues/1925#issuecomment-1887473292) to make it generic, while I also agree it should be DE agnostic and the same for all projects; so KDE should distribute it but apparently they are not interested and incorporate it instead inside KStatusNotifierItem (and IIUC also in something else you mentioned in your post).

For the reason above I created my ([yet another](https://xkcd.com/927/)) [version](https://github.com/qtilities/libdbusmenu-qtilities), hoping someone else shares the idea since KDE people (at least it seems) are not with us. So I used the suffix "-qtilities" to not add further confusion, but it would be nice find enough people to move in a common place, use the original name and collaborate for maintenance.

**Comment by redtide** [comment] 2024-03-14 12:06
@tsujan: thinking of it: if this is used only in LXQt SNI, why don't you incorporate it like [KSNI](https://github.com/KDE/kstatusnotifieritem/tree/master/src/libdbusmenu-qt) did?

For the menu issue I think it is working there (and so my version, which is a mix between lxqt qt plugin and KSNI), as I'm using it in my [OMGMounter](https://aur.archlinux.org/packages/omgmounter-git) app, which uses also a submenu.

**Comment by stefonarch** [comment] 2024-03-14 12:06
> I'm currently porting a few plasma plugins to Qt6.
> It would be great to not bundle the library.

We have an [issue](https://github.com/lxqt/libdbusmenu-lxqt/issues/9) with statusnotifier items not responding, but are not yet sure what the cause is, as it worked fine in the Qt5-based statusnotifierplugin in` lxqt-panel` for Qt6 apps.

**Comment by tsujan** [comment] 2024-03-14 12:14
> why don't you incorporate it like KSNI did?

It's used by more than one component, and it can be used outside LXQt.

**Comment by tsujan** [comment] 2024-03-14 12:21
> while I also agree it should be DE agnostic

It is already. The "-lxqt" in its name doesn't mean it depends on LXQt, as the "K" in KWindowSystem doesn't mean that it depends on KDE.

**Comment by redtide** [comment] 2024-03-14 12:41
> > while I also agree it should be DE agnostic
> 
> It is already. The "-lxqt" in its name doesn't mean it depends on LXQt, as the "K" in KWindowSystem doesn't mean that it depends on KDE.

AFAICS usually when a qt version is implemented you remove previous version support, which is not something some people would like to discover at some point that their app stop working. So being in LXQt, who guarantee that support still apply instead doing what LXQt only requires?
IMO it should be in a neutral context with other people working.

In fact, I had hard time to use KSNI and KWindowSystem because not available for Qt5. In the case of the former also requiring a version of KWindowSystem too recent that even Arch didn't have, but added only recently.

**Comment by redtide** [comment] 2024-03-14 12:44
> > I'm currently porting a few plasma plugins to Qt6.
> > It would be great to not bundle the library.
> 
> We have an [issue](https://github.com/lxqt/libdbusmenu-lxqt/issues/9) with statusnotifier item menus not responding but are not yet sure what the cause is, as it worked fine in the Qt5-based statusnotifierplugin in` lxqt-panel` for Qt6 apps.

I think because it was broken in the repo LXQt forked from, which also Arch uses and in fact libdbusmenu-qt6 in Arch is also broken.

**Comment by tsujan** [comment] 2024-03-14 12:57
> AFAICS usually when a qt version is implemented you remove previous version support,

When the main version of Qt is bumped (once in several years), it's natural to say goodbye to its older version when porting libraries to its new version. Everyone does it. But that "goodbye" doesn't make the older sources disappear from GitHub: it's among the released versions.

**Comment by redtide** [comment] 2024-03-14 13:17
> > I think because it was broken in the repo LXQt forked from
> 
> We fixed that.

> We have an https://github.com/lxqt/libdbusmenu-lxqt/issues/9 with statusnotifier item menus not responding but are not yet sure what the cause is, as it worked fine in the Qt5-based statusnotifierplugin in lxqt-panel for Qt6 apps.

I'm talking about this, for the Qt6 changes

**Comment by tsujan** [comment] 2024-03-14 13:20
> I'm talking about this, for the Qt6 changes

As @stefonarch said, we don't know its cause yet (I haven't started to look into it, being busy with other parts of LXQt).

**Comment by redtide** [comment] 2024-03-14 13:50
Yes, I was replying to him for the reason of the issue, which starts from the [desktop-app](https://github.com/desktop-app/libdbusmenu-qt/commit/af9fa001dac49eedc76e15613b67abfd097105f3) fork commits and probably also with missing updates/fixes which was added meanwhile in KSNI version.
I don't recall the details, I faced this when starting with my own fork.

**Comment by tsujan** [comment] 2024-12-10 15:48
We started to have our own version of "libdbusmenu" and already applied independent patches to it. Closing this…

**Closed by tsujan** 2024-12-10 15:48 UTC
Labels: help wanted
